export const GET_FILM = "GET_FILM";
export const GET_FILM_PLAYING = "GET_FILM_PLAYING";
export const GET_FILM_COMING = "GET_FILM_COMING";
export const GET_MOVIE_SHOWTIMES = "GET_MOVIE_SHOWTIMES";
export const GET_INFO_FILM = "GET_INFO_FILM";
export const EDIT_INFO_FILM = "EDIT_INFO_FILM";
export const SET_FILM_PARAM = "SET_FILM_PARAM";
